<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <PackageReference Include="Swashbuckle.AspNetCore" />
    <PackageReference Include="Asp.Versioning.Http" />
    <PackageReference Include="Asp.Versioning.Mvc.ApiExplorer" />
    <PackageReference Include="Microsoft.Extensions.Caching.Hybrid" />
    <PackageReference Include="Microsoft.Extensions.Diagnostics.HealthChecks.EntityFrameworkCore" />
    <PackageReference Include="OpenTelemetry.Extensions.Hosting" />
    <PackageReference Include="OpenTelemetry.Instrumentation.AspNetCore" />
    <PackageReference Include="OpenTelemetry.Instrumentation.Http" />
    <PackageReference Include="OpenTelemetry.Exporter.Console" />
    <PackageReference Include="OpenTelemetry.Exporter.OpenTelemetryProtocol" />
    <PackageReference Include="OpenTelemetry.Exporter.Prometheus.AspNetCore" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CleanArch.Api.Authentication\CleanArch.Api.Authentication.csproj" />
    <ProjectReference Include="..\..\BuildingBlocks\BuildingBlocks.csproj" />
    <ProjectReference Include="..\..\BuildingBlocks.RealTime\BuildingBlocks.RealTime.csproj" />
    <ProjectReference Include="..\..\Modules\Students\Students.Infrastructure\Students.Infrastructure.csproj" />
    <ProjectReference Include="..\..\Modules\Students\Students.Presentation\Students.Presentation.csproj" />
    <ProjectReference Include="..\..\Modules\Library\Library.Infrastructure\Library.Infrastructure.csproj" />
    <ProjectReference Include="..\..\Modules\Library\Library.Presentation\Library.Presentation.csproj" />
    <ProjectReference Include="..\..\Modules\TestPlans\TestPlans.Infrastructure\TestPlans.Infrastructure.csproj" />
    <ProjectReference Include="..\..\Modules\TestPlans\TestPlans.Presentation\TestPlans.Presentation.csproj" />
    <ProjectReference Include="..\..\Modules\TesterGuide\TesterGuide.Infrastructure\TesterGuide.Infrastructure.csproj" />
    <ProjectReference Include="..\..\Modules\TesterGuide\TesterGuide.Presentation\TesterGuide.Presentation.csproj" />
  </ItemGroup>

</Project>
