<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\TestPlans.Application\TestPlans.Application.csproj" />
    <ProjectReference Include="..\TestPlans.Contracts\TestPlans.Contracts.csproj" />
    <ProjectReference Include="..\..\TesterGuide\TesterGuide.Contracts\TesterGuide.Contracts.csproj" />
    <ProjectReference Include="..\..\..\BuildingBlocks.Outbox\BuildingBlocks.Outbox.csproj" />
    <ProjectReference Include="..\..\..\BuildingBlocks.Persistence\BuildingBlocks.Persistence.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

</Project>
