<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Asp.Versioning.Http" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Onboarding.Application\Onboarding.Application.csproj" />
  </ItemGroup>

</Project>
